### ISSUE TITLE
数据传输过程加密

### ISSUE THREAD

**Issue by david88558855** [KKRainbow/EasyTier#49]
数据传输过程加密

**Comment by KKRainbow** [comment]
目前 TCP / UDP 是明文传输，确实不大好，有必要实现加密，不过不会做的很复杂，大概率会做成预共享密钥的对称加密。

当前版本个人组网可以用 wireguard 链接，自带加密。

**Comment by KKRainbow** [comment]
done.
currently only aes-128-gcm is supported
