### ISSUE TITLE
rust1.75没有mips的工具链

### ISSUE THREAD

**Issue by 13653216371** [KKRainbow/EasyTier#53]
需要降低到1.74

**Comment by 13653216371** [comment]
error: failed to run custom build command for `ring v0.16.20`

有报错，能否把wg作为可选编译项从而跳过ring。在mips等小设备平台可以去掉它

**Comment by KKRainbow** [comment]
可能不只是 ring 的问题。easytier 自己也用了一些 rust 1.75+ 才有的特性。如果要支持 mips，可能还需要一些工作量

**Comment by lmq8267** [comment]
mips需要降级到1.72.1以下才行

**Comment by KKRainbow** [comment]
@lmq8267 嗯嗯，如果确实大家有这样的需求，我尝试做一些调整把用到新特性的地方改为可选编译

**Comment by lmq8267** [comment]
@KKRainbow 好的 非常期待

**Comment by KKRainbow** [comment]
@lmq8267 我试了下好像并不一定需要 rust 1.72，https://github.com/KKRainbow/EasyTier/tree/mips 这个分支现在可以走到链接步骤了

麻烦问下需要用 1.72 是因为有其他的限制么。

**Comment by lmq8267** [comment]
因为好像rust在1.72.1之后的版本里取消了对mips 的支持吧？ 更新日志里好像提到了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sijie.Sun ***@***.***&gt;
发送时间: 2024年5月3日 08:20
收件人: KKRainbow/EasyTier ***@***.***&gt;
抄送: lmq8267 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[KKRainbow/EasyTier] rust1.75没有mips的工具链 (Issue #53)





 
@lmq8267 我试了下好像并不一定需要 rust 1.72，https://github.com/KKRainbow/EasyTier/tree/mips 这个分支现在可以走到链接步骤了
 
麻烦问下需要用 1.72 是因为有其他的限制么。

**Comment by KKRainbow** [comment]
也不是完全取消，是降级到 Tier3 了，用 Cargo 指定编译 std 库似乎就可以了

cargo +nightly build -r --target=mipsel-unknown-linux-musl -Z build-std

**Comment by lmq8267** [comment]
那rustup target add $TARGET可能无法添加成功吧 &nbsp;1.72.1才有&nbsp;

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sijie.Sun ***@***.***&gt;
发送时间: 2024年5月3日 08:25
收件人: KKRainbow/EasyTier ***@***.***&gt;
抄送: lmq8267 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[KKRainbow/EasyTier] rust1.75没有mips的工具链 (Issue #53)





 
也不是完全取消，是降级到 Tier3 了，用 Cargo 指定编译 std 库似乎就可以了
 
cargo +nightly build -r --target=mipsel-unknown-linux-musl -Z build-std

**Comment by KKRainbow** [comment]
rustup 里添加的 target 都是预编译的，Tier3 的 target 确实不能通过 rustup 直接添加。

rustc 里还是有 mips target 的，所以只要手动编译下 std 就可以了

**Comment by KKRainbow** [comment]
编出来了。。。但是没有机器可以测试，难受

**Comment by KKRainbow** [comment]
[easytier-ubuntu-latest-mips-unknown-linux-musl (1).zip](https://github.com/KKRainbow/EasyTier/files/15198086/easytier-ubuntu-latest-mips-unknown-linux-musl.1.zip)
[easytier-ubuntu-latest-mipsel-unknown-linux-musl (1).zip](https://github.com/KKRainbow/EasyTier/files/15198087/easytier-ubuntu-latest-mipsel-unknown-linux-musl.1.zip)

我找了个机器试了一下，是可以的。默认只编 soft float 版本.
