### ISSUE TITLE
✨ 新功能：支持自定义 hostname

### ISSUE THREAD

**Issue by m1m1sha** [KKRainbow/EasyTier#89]
core 以及 gui 支持 hostname

- 自定义 hostname 作为高级设置
- 限制 hostname 只能存在字母数字和连字符（参考 windows 系统设备名称规则）
- 限制 hostname 最大长度
- gui 校验 hostname 数据和 core 校验数据防止出现错误
- core 命令行通过参数 `--host-name` 支持自定义

**Comment by m1m1sha** [comment]
> core 以及 gui 支持 hostname
> 
> * 自定义 hostname 作为高级设置
> * 限制 hostname 只能存在字母数字和连字符（参考 windows 系统设备名称规则）
> * 限制 hostname 最大长度
> * gui 校验 hostname 数据和 core 校验数据防止出现错误
> * core 命令行通过参数 `--host-name` 支持自定义

我已经开始进行

**Comment by KKRainbow** [comment]
这个功能不错
